name: flutter_firestorage
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.3
  firebase_storage: ^11.2.5
  path: ^1.8.3
  liquid_progress_indicator_v2: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
